# This is a basic workflow to help you get started with Actions

name: Build Code

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      #- name: Cache dependencies
      #  uses: actions/cache@v2
      #  with:
      #    path: |
      #      **/node_modules
      #    key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      #- name: Verify Cache
      #  run: npm cache verify
        
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build

      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com" 
          git commit -a -m "GH Action - Dist folder added"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
